import { SearchIcon, MicrophoneIcon} from '@heroicons/react/solid'
import { useRef } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from 'next/router'
import { useSession } from 'next-auth/react'

import IndexNavbar from '../components/IndexNavbar'


export default function Home() {

  const router = useRouter()
  const { data: session } = useSession()

  const inputRef = useRef(null)

  function search(e){
      e.preventDefault()

      const searchTerm = inputRef.current.value.trim()

      if(!searchTerm) return

      // blank search type (searchType=) will search normal, and searchType=image will search images
      router.push(`/search-results?searchTerm=${searchTerm}&searchType=`)  
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexNavbar/>  


      {session?.user?.email} <br />
      {session?.user?.image && <img src={session.user.image} className="h-10 w-10 p-1 rounded-full hover:bg-gray-200 cursor-pointer"/>}

      <form className="flex flex-col items-center mt-40">

        <Image src="https://i.dlpng.com/static/png/6561851_preview.png" width="400px" height="100px" objectFit='contain'/>

        <div className="flex items-center border border-gray-200 rounded-full w-full sm:max-w-[80%] lg:max-w-[60%] px-4 hover:shadow-lg focus:shadow-lg">

            <SearchIcon className="h-5 w-5 text-gray-500"/>
            <input ref={inputRef} className="flex-grow p-2 border-none outline-none"/>
            <MicrophoneIcon className="h-5 w-5 text-gray-500"/>

        </div>

        <div className='mt-5 mx-auto flex flex-col sm:flex-row w-[50%] justify-center space-x-4'>
            <button className='btn-search' onClick={search}>Google Search</button>
            <button className='btn-search'>I feeling Lucky</button>
        </div>

      </form>

    </div>
  )
}
